name: Build and Push user-service

on:
  push:
    branches:
      - qa

env:
  ORG_NAME: hufs-hexagon-talent
  PROJECT_NAME: study-room-reservation
  SERVICE_NAME: user-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.ORG_NAME }}/${{ env.PROJECT_NAME }}-${{ env.SERVICE_NAME }}:${{ github.sha }}
            ${{ github.ref == 'refs/heads/main' && format('ghcr.io/{0}/{1}-{2}:qa', env.ORG_NAME, env.PROJECT_NAME, env.SERVICE_NAME) || '' }}
          platforms: linux/amd64 #, linux/arm64/v8
